name: Test, Build, and Publish to PyPI

on:
  pull_request:
  workflow_dispatch:
    inputs:
      publish_pypi:
        description: 'Publish to PyPI'
        required: true
        default: false
        type: boolean


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.8.11"
    
    - name: Test
      run: |
        uv run pytest
    
    - name: Build
      run: uv build

    - name: Publish to PyPI
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.publish_pypi == 'true'
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: uv publish --verbose